excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://aanno.github.io
title: Netz- generation
tagline: A log of a decent IT nerd
description: A irregular blog of IT problem solutions I fell about.
paginate: 5
